git:
  paging:
    colorArg: always
    pager: "delta --dark --paging=never"

  parseEmoji: true

  truncateCopiedCommitHashesTo: 40

os:
  openLink: "${BROWSER} {{link}}"

notARepository: skip

gui:
  scrollHeight: 1
  scrollOffMargin: 2
  sidePanelWidth: 0.3
  mainPanelSplitMode: vertical
  enlargedSideViewLocation: top
  nerdFontsVersion: "3"
  showFileIcons: false
  showBranchCommitHash: true
  showDivergenceFromBaseBranch: arrowAndNumber

  # Theming:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - default
    searchingActiveBorderColor:
      - yellow
      - bold

    optionsTextColor:
      - blue

    selectedLineBgColor:
      - black

    cherryPickedCommitFgColor:
      - blue
    cherryPickedCommitBgColor:
      - default

    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - default

    unstagedChangesColor:
      - red

    defaultFgColor:
      - default

# Keybindings
keybinding:
  universal:
#     quit: q
#     quit-alt1: <c-c>
#     return: <esc>
#     quitWithoutChangingDirectory: Q
#     togglePanel: <tab>
    prevItem: k
    nextItem: j
    prevItem-alt: <disabled>
    nextItem-alt: <disabled>
    prevPage: <pgup>
    nextPage: <pgdown>
    scrollLeft: <disabled>
    scrollRight: <disabled>
    gotoTop: g
    gotoBottom: G
#     toggleRangeSelect: v
    rangeSelectUp: K
    rangeSelectDown: J
    prevBlock: h
    nextBlock: l
    prevBlock-alt: <disabled>
    nextBlock-alt: <disabled>
    nextBlock-alt2: <disabled>
    prevBlock-alt2: <disabled>
#     jumpToBlock:
#       - "1"
#       - "2"
#       - "3"
#       - "4"
#       - "5"
#     nextMatch: "n"
#     prevMatch: "N"
#     startSearch: /
#     optionMenu: <disabled>
    optionMenu-alt1: "?"
#     select: <space>
#     goInto: <enter>
#     confirm: <enter>
#     confirmInEditor: <a-enter>
#     remove: d
#     new: "n"
#     edit: e
#     openFile: o
    scrollUpMain: <c-k>
    scrollDownMain: <c-j>
    scrollUpMain-alt1: <disabled>
    scrollDownMain-alt1: <disabled>
    scrollUpMain-alt2: <disabled>
    scrollDownMain-alt2: <disabled>
#     executeCustomCommand: ":"
#     createRebaseOptionsMenu: m

    pushFiles: p
    pullFiles: <c-p>

    refresh: "#"
    createPatchOptionsMenu: P
#     nextTab: "]"
#     prevTab: "["
    nextScreenMode: "="
    prevScreenMode: "-"
    undo: u
    redo: <c-r>
    filteringMenu: <c-f>
    diffingMenu: W
    diffingMenu-alt: <disabled>
    copyToClipboard: <c-y>
    openRecentRepos: <disabled>
#     submitEditorText: <enter>
#     extrasMenu: "@"
    toggleWhitespaceInDiffView: <c-t>
#     increaseContextInDiffView: "}"
#     decreaseContextInDiffView: "{"
    openDiffTool: <disabled>
  status:
    checkForUpdate: U
#     recentRepos: <enter>
#     allBranchesLogGraph: a
  files:
#     commitChanges: c
#     commitChangesWithEditor: C
#     commitChangesWithoutHook: w
#     amendLastCommit: A
    findBaseCommitForFixup: <c-b>
#     confirmDiscard: x
#     ignoreFile: i
#     refreshFiles: r
#     stashAllChanges: s
#     viewStashOptions: S
#     toggleStagedAll: a
#     viewResetOptions: D
#     fetch: f
    toggleTreeView: "!"
    openMergeTool: <disabled>
    openStatusFilter: <c-s>
#     copyFileInfoToClipboard: "y"
  branches:
#     createPullRequest: o
#     viewPullRequestOptions: O
    copyPullRequestURL: <c-o>
#     checkoutBranchByName: c
    forceCheckoutBranch: C
    renameBranch: r
    rebaseBranch: R
#     mergeIntoCurrentBranch: M
    viewGitFlowOptions: <disabled>
#     fastForward: f
    createTag: t
    pushTag: p
    setUpstream: <c-u>
#     fetchRemote: f
#     sortOrder: s
#   worktrees:
#     viewWorktreeOptions: w
  commits:
#     squashDown: s
#     renameCommit: r
#     renameCommitWithEditor: R
    viewResetOptions: U
#     markCommitAsFixup: f
#     createFixupCommit: F
#     squashAboveCommits: S
    moveDownCommit: <c-n>
    moveUpCommit: <c-p>
#     amendToCommit: A
#     resetCommitAuthor: a
#     pickCommit: p
    revertCommit: T
    cherryPickCopy: Y
    pasteCommits: P
#     markCommitAsBaseForRebase: B
    tagCommit: t
    checkoutCommit: c
    resetCherryPick: <disabled>
#     copyCommitAttributeToClipboard: "y"
#     openLogMenu: <c-l>
#     openInBrowser: o
#     viewBisectOptions: b
#     startInteractiveRebase: i
#   amendAttribute:
#     resetAuthor: a
#     setAuthor: A
#     addCoAuthor: c
  stash:
    popStash: p
#     renameStash: r
#   commitFiles:
#     checkoutCommitFile: c
#   main:
#     toggleSelectHunk: a
#     pickBothHunks: b
#     editSelectHunk: E
  submodules:
#     init: i
    update: U
#     bulkMenu: b
#   commitMessage:
#     commitMenu: <c-o>
