backend = "full"
color_space = "labmixed"
palette = "harddark16"

[templates]
alacritty.template = "templates/colors_alacritty.toml"
alacritty.target = "~/.config/alacritty/alacritty_wallust.toml"

wezterm.template = "templates/colors_wezterm.toml"
wezterm.target = "~/.config/wezterm/colors/Wallust.toml"

zellij.template = "templates/colors_zellij.kdl"
zellij.target = "~/.config/zellij/themes/wallust.kdl"

glow.template = "templates/colors_glow.json"
glow.target = "~/.config/glow/glow_wallust.json"

hypr.template = "templates/colors_hypr.conf"
hypr.target = "~/.config/hypr/hypr_wallust.conf"

oomox.template = "templates/colors_oomox"
oomox.target = "~/.config/oomox/colors/wallust"

rofi.template = "templates/colors_rofi.rasi"
rofi.target = "~/.config/rofi/colors.rasi"

swaync.template = "templates/colors_swaync.css"
swaync.target = "~/.config/swaync/swaync_wallust.css"

tty.template = "templates/colors_tty.sh"
tty.target = "~/.cache/wallust/colors_tty.sh"

waybar.template = "templates/colors_waybar.css"
waybar.target = "~/.config/waybar/shared/colors.css"

waybar_clock.template = "templates/colors_waybar_clock.jsonc"
waybar_clock.target = "~/.config/waybar/shared/clock_wallust.jsonc"

kvantum_kvconfig.template = "templates/colors_kvantum.kvconfig"
kvantum_kvconfig.target = "~/.config/Kvantum/Wallust/Wallust.kvconfig"

kvantum_svg.template = "templates/colors_kvantum.svg"
kvantum_svg.target = "~/.config/Kvantum/Wallust/Wallust.svg"

cava.template = "templates/colors_cava"
cava.target = "~/.config/cava/config"

gnuplotrc.template = "templates/colors_gnuplotrc"
gnuplotrc.target = "~/.config/gnuplot/gnuplotrc"

zathurarc.template = "templates/colors_zathurarc"
zathurarc.target = "~/.config/zathura/zathurarc_wallust"

kdeglobals.template = "templates/colors_kdeglobals"
kdeglobals.target = "~/.config/kdeglobals"

colors_sh.template = "templates/colors.sh"
colors_sh.target = "~/.cache/wallust/colors.sh"

fish.template = "templates/colors_fish.fish"
fish.target = "~/.cache/wallust/colors_fish.fish"

neopywal.template = "templates/colors_neopywal.vim"
neopywal.target = "~/.cache/wallust/colors_neopywal.vim"

bento.template = "templates/colors_bento.css"
bento.target = "~/.local/sources/Reds/Bento/assets/style/colors.css"

waterfall.template = "templates/colors_waterfall.css"
waterfall.target = "~/.librewolf/default/chrome/userChrome.css"
