style = "full"
invert = true
show_tabs = false
show_help = false
enter_accept = false
keymap_mode = "vim-insert"
keymap_cursor = { emacs = "blink-underline", vim_insert = "blink-bar", vim_normal = "blink-block" }

common_prefix = [ "sudo", "doas" ]
history_filter = [
  "^reboot",
  "^shutdown",
  "^pwd",
  "^exit",
  "^q",
  "^cl",
  "^history",
  "^ls|^la|^ll|^lt|^l.|^eza",
  "^cd -",
  "^cd ..",
  "^echo.*"
]
