style = "compact"
invert = true
show_tabs = false
enter_accept = false
keymap_mode = "vim-insert"
keymap_cursor = { emacs = "blink-underline", vim_insert = "blink-bar", vim_normal = "blink-block" }

history_filter = [
  "^reboot$",
  "^shutdown$",
  "^pwd$",
  "^exit$",
  "^q$",
  "^cl$",
  "^history$",
  "^ls|^la|^ll|^lt",
  "^cd -$",
  "^cd ..$",
]
