# vim:fileencoding=utf-8:foldmethod=marker

#: Flavor {{{
[flavor]
use = ""
#: }}}
#: Manager {{{
[manager]
cwd = { fg = "cyan" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { fg = "white", reversed = true }

# Find
find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { bg = "reset", fg = "magenta", bold = true, italic = true }

# Marker
marker_copied   = { bg = "lightyellow",  fg = "lightyellow" }
marker_cut      = { bg = "lightred",     fg = "lightred" }
marker_marked   = { bg = "lightcyan",    fg = "lightcyan" }
marker_selected = { bg = "lightmagenta", fg = "lightmagenta" }

# Tab
tab_active   = { fg = "blue", bold = true, reversed = true }
tab_inactive = { bold = true }
tab_width    = 1

# Count
count_copied   = { bg = "green", fg = "white" }
count_cut      = { bg = "red", fg = "white" }
count_selected = { bg = "yellow", fg = "white" }

# Border
border_symbol = "│"
border_style  = { fg = "gray" }

# Highlighting
syntect_theme = ""
#: }}}
#: Status {{{
[status]
separator_open  = ""
separator_close = ""
separator_style = { bg = "black", fg = "black" }

# Mode
mode_normal = { bg = "blue",    fg = "black", bold = true }
mode_select = { bg = "magenta", fg = "black", bold = true }
mode_unset  = { bg = "red",     fg = "black", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { bg = "black", fg = "blue" }
progress_error  = { bg = "black",  fg = "red" }

# Permissions
permissions_t = { fg = "green",    bold = true }
permissions_r = { fg = "yellow",   bold = true }
permissions_w = { fg = "red",      bold = true }
permissions_x = { fg = "cyan",     bold = true }
permissions_s = { fg = "darkgray", bold = true }
#: }}}
#: Select {{{
[select]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}
#: }}}
#: Input {{{
[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }
#: }}}
#: Completion {{{
[completion]
border   = { fg = "blue" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = " "
icon_folder  = " "
icon_command = " "
#: }}}
#: Tasks {{{
[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", underline = true }
#: }}}
#: Which {{{
[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "cyan", bold = true }
rest            = { fg = "darkgray" }
desc            = { fg = "reset" }
separator       = "  "
separator_style = { fg = "lightyellow", bold = true }
#: }}}
#: Help {{{
[help]
on      = { fg = "blue" }
run     = { fg = "magenta" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { bg = "white", fg = "black" }
#: }}}
#: Notify {{{
[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""
#: }}}
#: File-specific styles {{{
[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "cyan" },

	# Media
	{ mime = "{audio,video}/*", fg = "yellow" },

	# Archives
	{ mime = "application/*zip", fg = "red" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "red" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "green" },

	# Fallback
	# { name = "*", fg = "white" },
	{ name = "*/", fg = "blue" }
]
#: Icon styles {{{
[icon]
rules = [
	# Programming
	{ name = "*.c"    , text = " ", fg = "lightblue" },
	{ name = "*.cpp"  , text = " ", fg = "cyan" },
	{ name = "*.class", text = " ", fg = "red" },
	{ name = "*.cs"   , text = "󰌛 ", fg = "magenta" },
	{ name = "*.css"  , text = " ", fg = "lightcyan" },
	{ name = "*.elm"  , text = " ", fg = "lightcyan" },
	{ name = "*.fish" , text = " ", fg = "lightyellow" },
	{ name = "*.go"   , text = " ", fg = "cyan" },
	{ name = "*.h"    , text = " ", fg = "lightmagenta" },
	{ name = "*.hpp"  , text = " ", fg = "lightmagenta" },
	{ name = "*.html" , text = " ", fg = "lightyellow" },
	{ name = "*.jar"  , text = " ", fg = "red" },
	{ name = "*.java" , text = " ", fg = "red" },
	{ name = "*.js"   , text = " ", fg = "yellow" },
	{ name = "*.jsx"  , text = " ", fg = "cyan" },
	{ name = "*.lua"  , text = " ", fg = "lightcyan" },
	{ name = "*.nix"  , text = " ", fg = "lightblue" },
	{ name = "*.nu"   , text = "> ", fg = "green" },
	{ name = "*.php"  , text = " ", fg = "lightmagenta" },
	{ name = "*.py"   , text = " ", fg = "yellow" },
	{ name = "*.rb"   , text = " ", fg = "red" },
	{ name = "*.rs"   , text = " ", fg = "lightyellow" },
	{ name = "*.sbt"  , text = " ", fg = "darkgray" },
	{ name = "*.scala", text = " ", fg = "red" },
	{ name = "*.scss" , text = " ", fg = "lightmagenta" },
	{ name = "*.sh"   , text = " ", fg = "darkgray" },
	{ name = "*.swift", text = " ", fg = "lightyellow" },
	{ name = "*.ts"   , text = " ", fg = "cyan" },
	{ name = "*.tsx"  , text = " ", fg = "lightblue" },
	{ name = "*.vim"  , text = " ", fg = "green" },
	{ name = "*.vue"  , text = "󰡄 ", fg = "lightgreen" },

	# Text
	{ name = "*.conf", text = " ", fg = "darkgray" },
	{ name = "*.ini" , text = " ", fg = "darkgray" },
	{ name = "*.json", text = " ", fg = "lightyellow" },
	{ name = "*.kdl" , text = " ", fg = "darkgray" },
	{ name = "*.md"  , text = " ", fg = "white" },
	{ name = "*.toml", text = " ", fg = "lightyellow" },
	{ name = "*.txt" , text = " ", fg = "green" },
	{ name = "*.yaml", text = " ", fg = "darkgray" },
	{ name = "*.yml" , text = " ", fg = "darkgray" },

	# Archives
	{ name = "*.7z" , text = " ", fg = "red" },
	{ name = "*.bz2", text = " ", fg = "red" },
	{ name = "*.gz" , text = " ", fg = "red" },
	{ name = "*.rar", text = " ", fg = "red" },
	{ name = "*.tar", text = " ", fg = "red" },
	{ name = "*.xz" , text = " ", fg = "red" },
	{ name = "*.zip", text = " ", fg = "red" },

	# Images
	{ name = "*.HEIC", text = " ", fg = "lightmagenta" },
	{ name = "*.avif", text = " ", fg = "lightmagenta" },
	{ name = "*.bmp" , text = " ", fg = "lightmagenta" },
	{ name = "*.gif" , text = " ", fg = "lightmagenta" },
	{ name = "*.ico" , text = " ", fg = "yellow" },
	{ name = "*.jpeg", text = " ", fg = "lightmagenta" },
	{ name = "*.jpg" , text = " ", fg = "lightmagenta" },
	{ name = "*.png" , text = " ", fg = "lightmagenta" },
	{ name = "*.svg" , text = " ", fg = "lightyellow" },
	{ name = "*.webp", text = " ", fg = "lightmagenta" },

	# Movies
	{ name = "*.avi" , text = " ", fg = "lightyellow" },
	{ name = "*.mkv" , text = " ", fg = "lightyellow" },
	{ name = "*.mov" , text = " ", fg = "lightyellow" },
	{ name = "*.mp4" , text = " ", fg = "lightyellow" },
	{ name = "*.webm", text = " ", fg = "lightyellow" },

	# Audio
	{ name = "*.aac" , text = " ", fg = "lightcyan" },
	{ name = "*.flac", text = " ", fg = "lightcyan" },
	{ name = "*.m4a" , text = " ", fg = "lightcyan" },
	{ name = "*.mp3" , text = " ", fg = "lightcyan" },
	{ name = "*.ogg" , text = " ", fg = "lightcyan" },
	{ name = "*.wav" , text = " ", fg = "lightcyan" },

	# Documents
	{ name = "*.csv" , text = " ", fg = "lightgreen" },
	{ name = "*.doc" , text = " ", fg = "lightblue" },
	{ name = "*.doct", text = " ", fg = "lightblue" },
	{ name = "*.docx", text = " ", fg = "lightblue" },
	{ name = "*.dot" , text = " ", fg = "lightblue" },
	{ name = "*.ods" , text = " ", fg = "green" },
	{ name = "*.ots" , text = " ", fg = "green" },
	{ name = "*.pdf" , text = " ", fg = "red" },
	{ name = "*.pom" , text = " ", fg = "red" },
	{ name = "*.pot" , text = " ", fg = "lightyellow" },
	{ name = "*.potx", text = " ", fg = "lightyellow" },
	{ name = "*.ppm" , text = " ", fg = "lightmagenta" },
	{ name = "*.ppmx", text = " ", fg = "red" },
	{ name = "*.pps" , text = " ", fg = "red" },
	{ name = "*.ppsx", text = " ", fg = "red" },
	{ name = "*.ppt" , text = " ", fg = "red" },
	{ name = "*.pptx", text = " ", fg = "red" },
	{ name = "*.xlc" , text = " ", fg = "green" },
	{ name = "*.xlm" , text = " ", fg = "green" },
	{ name = "*.xls" , text = " ", fg = "green" },
	{ name = "*.xlsm", text = " ", fg = "green" },
	{ name = "*.xlsx", text = " ", fg = "green" },
	{ name = "*.xlt" , text = " ", fg = "green" },

	# Lockfiles
	{ name = "*.lock", text = " ", fg = "darkgray" },

	# Misc
	{ name = "*.bin", text = " ", fg = "red" },
	{ name = "*.exe", text = " ", fg = "red" },
	{ name = "*.pkg", text = " ", fg = "red" },

	# Dotfiles
	{ name = "*.DS_Store"     , text = " ", fg = "darkgray" },
	{ name = "*.bash_profile" , text = " ", fg = "lightgreen" },
	{ name = "*.bashprofile"  , text = " ", fg = "lightgreen" },
	{ name = "*.bashrc"       , text = " ", fg = "lightgreen" },
	{ name = "*.gitattributes", text = " ", fg = "darkgray" },
	{ name = "*.gitignore"    , text = " ", fg = "darkgray" },
	{ name = "*.gitmodules"   , text = " ", fg = "darkgray" },
	{ name = "*.vimrc"        , text = " ", fg = "green" },
	{ name = "*.zprofile"     , text = " ", fg = "lightgreen" },
	{ name = "*.zshenv"       , text = " ", fg = "lightgreen" },
	{ name = "*.zshrc"        , text = " ", fg = "lightgreen" },

	# Named files
	{ name = "*COPYING"      , text = "󰿃 ", fg = "yellow" },
	{ name = "*Containerfile", text = "󰡨 ", fg = "lightblue" },
	{ name = "*Dockerfile"   , text = "󰡨 ", fg = "lightblue" },
	{ name = "*LICENSE"      , text = "󰿃 ", fg = "yellow" },

	# Directories
	{ name = "*.config/"    , text = " " },
	{ name = "*.git/"       , text = " " },
	{ name = "*Desktop/"    , text = " " },
	{ name = "*Development/", text = " " },
	{ name = "*Documents/"  , text = " " },
	{ name = "*Downloads/"  , text = " " },
	{ name = "*Library/"    , text = " " },
	{ name = "*Movies/"     , text = " " },
	{ name = "*Music/"      , text = " " },
	{ name = "*Pictures/"   , text = " " },
	{ name = "*Public/"     , text = " " },
	{ name = "*Videos/"     , text = " " },

	# Default
	{ name = "*" , text = "" },
	{ name = "*/", text = "" },
]
#: }}}
#: }}}
