[colors]
background = "#1A1B26"
foreground = "#A9B1D6"
cursor_bg = "#A9B1D6"
cursor_fg = "#1A1B26"
cursor_border = "#A9B1D6"
selection_fg = "#AD8EE6"
selection_bg = "#12131B"
scrollbar_thumb = "#76767D"
split = "#A9B1D6"
compose_cursor = "#FF9E64"
copy_mode_active_highlight_bg = { Color = "#32344A" }
copy_mode_active_highlight_fg = { Color = "#1A1B26" }
copy_mode_inactive_highlight_bg = { Color = "#9ECE6A" }
copy_mode_inactive_highlight_fg = { Color = "#A9B1D6" }
quick_select_label_bg = { Color = "#E0AF68" }
quick_select_label_fg = { Color = "#A9B1D6" }
quick_select_match_bg = { Color = "#7AA2F7" }
quick_select_match_fg = { Color = "#A9B1D6" }

ansi = [ "#32344A", "#F7768E", "#9ECE6A", "#E0AF68", "#7AA2F7", "#AD8EE6", "#449DAB", "#787C99" ]
brights = [ "#444B6A", "#FF7A93", "#B9F27C", "#FF9E64", "#7DA6FF", "#BB9AF7", "#0DB9D7", "#ACB0D0" ]
