# -------------------------------------------------------------------- #

#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝

# -------------------------------------------------------------------- #

# Import pywal colors:
import = ["/home/Reds/.cache/wal/colors-alacritty.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 300
blink_timeout = 0
thickness = 0.3
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 12

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Up"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Down"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Left"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Right"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageUp"
mode = "~Alt"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageDown"
mode = "~Alt"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "U"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "D"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[scrolling]
history = 100000
multiplier = 5

[window]
decorations = "none"
dynamic_padding = true
opacity = 1.0
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0
