# -------------------------------------------------------------------- #

#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝

# -------------------------------------------------------------------- #

# Import pywal colors:
import = ["/home/Reds/.config/alacritty/alacritty_wallust.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
blink_interval = 300
blink_timeout = 0
thickness = 0.3
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "alacritty"

[scrolling]
history = 100000
multiplier = 5

[window]
decorations = "none"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10

[window.position]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[font]
size = 14.5
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
	{ action = "Paste", mods = "Alt", key = "p" }, # Copy selection.
	{ action = "Copy",  mods = "Alt", key = "y" }, # Paste.
]
