# vim:fileencoding=utf-8:foldmethod=marker:foldenable

# ---------------------------------------------------------- #

# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝

# ---------------------------------------------------------- #

#: Formatting {{{
format = """
$os$username$hostname\
$directory\
$shell\
$git_branch\
$git_status\
$all\
$line_break\
`-\
$cmd_duration$character
"""
#: }}}
#: Os {{{
[os]
disabled = false
style = "fg:red bold"
format = '[\[$symbol\] ]($style)'

[os.symbols]
Alpaquita = "Alpaquita"
Alpine = "Alpine"
Amazon = "Amazon"
Android = "Android"
Arch = "Arch"
Artix = "Artix"
CentOS = "CentOS"
Debian = "Debian"
DragonFly = "DragonFly"
Emscripten = "Emscripten"
EndeavourOS = "EndeavourOS"
Fedora = "Fedora"
FreeBSD = "FreeBSD"
Garuda = "Garuda"
Gentoo = "Gentoo"
HardenedBSD = "HardenedBSD"
Illumos = "Illumos"
Linux = "Linux"
Mabox = "Mabox"
Macos = "Macos"
Manjaro = "Manjaro"
Mariner = "Mariner"
MidnightBSD = "MidnightBSD"
Mint = "Mint"
NetBSD = "NetBSD"
NixOS = "NixOS"
OpenBSD = "OpenBSD"
OpenCloudOS = "OpenCloudOS"
openEuler = "openEuler"
openSUSE = "openSUSE"
OracleLinux = "OracleLinux"
Pop = "Pop"
Raspbian = "Raspbian"
Redhat = "Redhat"
RedHatEnterprise = "RedHatEnterprise"
Redox = "Redox"
Solus = "Solus"
SUSE = "SUSE"
Ubuntu = "Ubuntu"
Unknown = "Unknown"
Windows = "Windows"
#: }}}
#: Username {{{
[username]
disabled = false
show_always = true
style_user = "fg:blue bold"
style_root = "fg:blue bold"
format = '[$user]($style)'
#: }}}
#: Hostname {{{
[hostname]
disabled = false
ssh_only = false
ssh_symbol = "SSH:"
style = "fg:blue bold"
format = ' at [$ssh_symbol$hostname ]($style)'
#: }}}
#: Directory {{{
[directory]
read_only = "RO"
truncation_length = 3
truncation_symbol = "../"
style = "fg:cyan bold"
format = 'on [$path ]($style)'
#: }}}
#: Shell {{{
[shell]
disabled = false
bash_indicator = 'bash'
cmd_indicator = 'cmd'
elvish_indicator = 'esh'
fish_indicator = 'fish'
ion_indicator = 'ion'
nu_indicator = 'nu'
powershell_indicator = 'psh'
tcsh_indicator = 'tsh'
xonsh_indicator = 'xsh'
zsh_indicator = 'zsh'
unknown_indicator = '?sh'
style = "fg:green bold"
format = 'using [$indicator ]($style)'
#: }}}
#: Git {{{
[git_commit]
tag_symbol = "tag:"

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
#: }}}
#: Plain text {{{
[aws]
symbol = "aws "

[azure]
symbol = "az "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[golang]
symbol = "go "

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[raku]
symbol = "raku "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[typst]
symbol = "typst "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
#: }}}
#: Cmd duration {{{
[cmd_duration]
disabled = false
style = "fg:yellow bold"
format = 'took [$duration]($style) '
#: }}}
#: Line break & Character {{{
[line_break]
disabled = false

[status]
symbol = "[x](bold red) "

[character]
disabled = false
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold yellow)"
vimcmd_visual_symbol = '[<](bold purple)'
vimcmd_replace_symbol = '[<](bold purple)'
vimcmd_replace_one_symbol = '[<](bold purple)'
#: }}}
